services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: planner-web
    restart: unless-stopped

    # Expose port 3000 on the host
    ports:
      - "3000:3000"

    # Load environment variables for production
    env_file:
      - .env.build

    environment:
      NODE_ENV: production
      #DATABASE_URL: ${DATABASE_URL}

    volumes:
      - ./files:/app/files
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Attach to the shared external network with Postgres
    networks:
      - app-net

networks:
  app-net:
    external: true
